version: "3.9"

services:
  web:
    build: .
    command: python lunchplace/manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/lunchplace
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - ./source:/app \
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 3306

volumes:
  postgres_data: